import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { InlineTodoWithMachine } from "./tutors/inlineTodoWithMachine";
import { SharedStateTodo } from "./tutors/sharedStateTodo";
import { SimpleTest } from "./tutors/simpleTest";
import { SimpleValidation } from "./tutors/simpleValidation";
import { SimpleVideoPlayer } from "./tutors/simpleVideoPlayer";
import { TodosBegin } from "./tutors/todosBegin";
import { TodosFinish } from "./tutors/todosFinish";
import { TodosMiddle } from "./tutors/todosMiddle";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>XState React Samples</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          <SimpleTest title="Simple Test" />
          <TodosBegin title="Todos Begin" />
          <TodosMiddle title="Todos Middle" />
          <TodosFinish title="Todos Finish" />
          <SimpleValidation title="Simple Validation" />
          <SimpleVideoPlayer title="Simple Video Player" />
          <InlineTodoWithMachine title="Inline Todo With Machine" />
          <SharedStateTodo title="Shared State Todo" />
        </div>
      </main>
    </>
  );
}
